services:
  pwnage_server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GOOGLE_APPLICATION_CREDENTIALS: /home/node/.config/gcloud/application_default_credentials.json
      PATREON_CAMPAIGN_ID: ${PATREON_CAMPAIGN_ID}
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/srv/server/src
      - "${GOOGLE_APPLICATION_CREDENTIALS}:/home/node/.config/gcloud/application_default_credentials.json:ro"
