name: pwnage
description: "Pwnage RSS viewer"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.2
  google_fonts: ^6.3.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  freezed_lint: ^0.0.10
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/patreon_logo.svg
    - assets/icons/youtube_logo.svg
