name: pwnage
description: "Teh Pwnage Feed viewer"
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  flutter_html: ^3.0.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  transparent_image: ^2.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  freezed_lint: ^0.0.10
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/patreon_logo.svg
    - assets/icons/youtube_logo.svg
    - assets/images/jeremy_lol.webp
    - assets/images/silhouette.webp

flutter_launcher_icons:
  image_path: "assets/images/app_icon/default.webp"

  android: true
  image_path_android: "assets/images/app_icon/default.webp"
  adaptive_icon_foreground: "assets/images/app_icon/android_adaptive_foreground.webp"
  adaptive_icon_background: "#000000"
  adaptive_icon_monochrome: "assets/images/app_icon/android_adaptive_foreground.webp"

  ios: true
  remove_alpha_ios: true
  background_color_ios: "#000000"
