FROM node:24-alpine3.21

ENV NODE_ENV $NODE_ENV
ENV BASE_URL $BASE_URL

# Install dependencies in the development image
WORKDIR /srv/server
RUN mkdir uploads
COPY package*.json ./
RUN npm install

COPY tsconfig.json ./

EXPOSE 8080

CMD npm run dev
